[build.environment]
  NODE_VERSION = "16"
  NETLIFY_USE_YARN = "true"

[build]
  publish = "build"
  command = "yarn build"

[[headers]]
  for = "\.(js|css)$"
  [headers.values]
    cache-control = '''
    public,
    max-age=2592000'''
