name: Frontend Weekly

concurrency:
  group: build_and_deploy
  cancel-in-progress: true

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmmirror.com/
          cache: yarn

      ### if use Go ###

      # - name: Set up Go 1.14
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: 1.14
      #   id: go

      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      ### if use pnpm ###

      # - name: Cache ~/.pnpm-store
      #   uses: actions/cache@v3
      #   env:
      #     cache-name: cache-pnpm-store
      #   with:
      #     path: ~/.pnpm-store
      #     key: ${{ runner.os }}-${{ matrix.node-version }}-test-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-${{ matrix.node-version }}-test-${{ env.cache-name }}-
      #       ${{ runner.os }}-${{ matrix.node-version }}-test-
      #       ${{ runner.os }}-

      # - name: Setup pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: latest

      # - name: Install deps
      #   run: pnpm i --frozen-lockfile

      # - name: Build
      #   run: pnpm build

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --production --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          full_commit_message: ${{ github.event.head_commit.message }}
