name: Frontend Weekly
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Build
        run: |
          npm install yarn
          yarn
          yarn build
      - name: Deploy
        use: peaceiris/actions-gh-pages@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: main
          full_commit_message: ${{ github.event.head_commit.message }}
